### PR TITLE
Add a colon to the paymentPointer option in readme

### PR DESCRIPTION
**Pull request by Shaun-Regenbaum**
There was a colon missing from the read me in the options section, so I added it.

### CODE REVIEW

**Comment by VladimirMikulic** [comment]
Nice catch @Shaun-Regenbaum. Thanks!

**Comment by Shaun-Regenbaum** [comment]
Thank you for the awesome library! I also might recommend making it clearer in the standalone usage that you dont need both module import and require, only one of them, some beginners (like me) might get confused at the repeated decleration errors.

**Comment by VladimirMikulic** [comment]
Whoops, my bad! Thanks for pointing that out! Sorry for the confusion.

**Comment by Shaun-Regenbaum** [comment]
I actually have a quick question if you are willing to spare some time.
How would I go about sending exactly one monetization event? Meaning how do I invoke montizationStop with your library?

**Comment by VladimirMikulic** [comment]
@Shaun-Regenbaum Check out [this](https://github.com/VladimirMikulic/tessy#web-monetization) section. (`emit` function)

**Comment by Shaun-Regenbaum** [comment]
In order to see a monetization stopped event would it be helpful for others to create in monetization.js
`const dispatchStopEvt = emit.bind(null, 'monetizationstopped');`

and to add it to pauseMonetization:
`const pauseMonetization = (pauseTime = null) => {
  const intervalID = Store.getItem('monInterval');
  clearInterval(intervalID);
  Store.setItem('monInterval', null);
  dispatchStopEvt();
  if (!pauseTime) return;
  setTimeout(resumeMonetization, pauseTime);
};`
 ?

**Comment by Shaun-Regenbaum** [comment]
Also in that line, it seems that is an official event in the [API](https://webmonetization.org/docs/api) if you agree I can create those changes and submit them.

**Comment by VladimirMikulic** [comment]
If I understand this correctly, you would like to have events logged in console?

**Comment by Shaun-Regenbaum** [comment]
I mean, to the best of my understanding, in the current state of the code there is no monetizationstop event, just the ability to pause monetization? Don't you need to bind the stoppage to an event? Otherwise how would I add an eventlistener to the monetizationstop event?

**Comment by VladimirMikulic** [comment]
You can actually emit `monetizationstop` event by using `emit("monetizationstop")` and listen for this event using: `document.monetization.addEventListener("monetizationstop", handlerFn)`. I hope this clears your doubt.

**Comment by Shaun-Regenbaum** [comment]
Aha, I think I get it now.

**Pull request merged**
